//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JacksonApi.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JacksonSiteEntities : DbContext
    {
        public JacksonSiteEntities()
            : base("name=JacksonSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Act> Acts { get; set; }
        public virtual DbSet<Volume> Volumes { get; set; }
        public virtual DbSet<VolumeText> VolumeTexts { get; set; }
    }
}
